name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Upload index.js to GitHub release
        uses: svenstaro/upload-release-action@2.11.2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./index.js
          asset_name: index.js
          tag: build-${{ github.run_id }}
          overwrite: true
          make_latest: true

      - name: Send Discord Notification
        if: always() # executa mesmo se o job falhar
        run: |
          STATUS=${{ job.status }}
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\":\":robot: CI finalizado com status: **${STATUS}** no repositório ${{ github.repository }} (commit: ${{ github.sha }})\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}